### ISSUE TITLE
Accelerated Keccak in RISCV

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#1241]
- [x] Implement keccak in powdr stdlib https://github.com/powdr-labs/powdr/issues/906
- [x] Add a keccak syscall to our RISCV runtime https://github.com/powdr-labs/powdr/issues/1246
- [x] Fork tinykeccak (and/or other Keccak) crates and use the powdr accelerated syscall https://github.com/powdr-labs/powdr/issues/1247

**Comment by leonardoalt** [comment]
Done
