### ISSUE TITLE
PIL Milestone: identities-only PIL

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#1249]
- [ ] Implement permutation argument in PIL
- [ ] Implement lookup argument in PIL
- [ ] Implement connect argument in PIL
- [ ] Replace built-in permutation by PIL permutation in stdlib
- [ ] Replace built-in lookup by PIL permutation in stdlib
- [ ] Replace built-in connect by PIL permutation in stdlib
