### ISSUE TITLE
Auto-generated prover functions

### ISSUE THREAD

**Issue by chriseth** [powdr-labs/powdr#2066]
It shouldn't be too difficult to auto-generate prover functions for witness generation.

We essentially loop over row deltas and identities like in runtime witgen, just that instead of computing values, we emit code that computes these values.

For each cell, we store:
- Range constraints (might be constant)
- If its known or not

Once each column has `period` many known cells, the code is complete.

In order to work with the fixed (and other) lookups, we need to know how many of the input values need to be known for the lookup to always succeed (remember, in this one, we cannot just try out if it works). For this we need an interface of the kind "Given these range constraints on those columns (and knowing the values at runtime), can the rest of the columns be uniquely determined?"

This interface is also the one we need to implement for the auto witgen code generation. We need to try to build the code and answer "yes" if we can generate code that uniquely determines all missing columns on the latch row.

----

TODO:

- [x] optimized impl for certain fields ( #2253 )
- [x] implement "can always answer call" for certain machines and use it for decision to perform call ( #2255 #2256 )
- [x] support non-rectangular block shapes ( #2281 )
- [x] support branching ( #2274 )
- [ ] support dynamic machine
- [x] detect certain prover functions to be "ok" (especially the regular riscv query function)
- [x] annotate prover functions with inputs, outputs and conditions and jit-compile them from pil to rust.

IDEAS:
- [ ] try compiling with 'no_std' to see if compilation is faster.
- [ ] check if using `add_no_canonicalize_trashing_input` is really faster, esecially since we want to bring the result into canonical form again anyway.
