### ISSUE TITLE
powdr 0.1 release

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#974]
Items that are probably needed for the release

- [x] tidy up repo
- [x] have crate names that make sense
- [x] package info https://github.com/powdr-labs/powdr/pull/963
- [x] verifier in CLI + docs
- [x] verifier in lib (exposed via `backend`) + docs
- [x] check if there are more crates that need to be exposed in the `powdr` crate (ast)
- [x] more docs examples https://github.com/powdr-labs/powdr/issues/1225
- [x] run examples via `cargo run --example`
- [x] maybe revme as example https://github.com/powdr-labs/powdr/issues/1225
- [x] Halo2 conversion soundness bug: https://github.com/powdr-labs/powdr/issues/1036
- [x] export verifier (Solidity for Halo2, circom for estark) https://github.com/powdr-labs/powdr/issues/1226
- [x] make sure https://github.com/leonardoalt/merkle-tree-powdr is working

**Comment by leonardoalt** [comment]
Done!
